baseURL = "https://example.com"
languageCode = "en-us"
title = "Archie-solarized"
paginate = 5
theme="archie-solarized"
copyright = "Â© H. Cartiaux"
pygmentsstyle = "monokai"
pygmentsStyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/hcartiaux/hugo-theme-archie-solarized)"
    mathjax = false # enable MathJax support
    katex = true # enable KaTeX support

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/hcartiaux/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/hcartiaux/hugo-theme-archie-solarized"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/hyacinthecartiaux/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/hcartiaux/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
